### ISSUE TITLE
[ENHANCEMENT] Allow for collapsing/expanding all categories in modlist.txt

### ISSUE THREAD

**Issue by nollidnosnhoj** [phinocio/loadorderlibrary-frontend#16]
As someone who usually like to look at the lord-order of modlists from Wabbajack, a nice feature/enhancement is to allow users to collapse all categories in the modlist.txt file. 

For example, I'm interested in a modlist I found in Wabbajack, but I'm curious about what quest mods does the modlist use. Currently, I would have to scroll through the modlist, which can be huge (more than 1000 mods), to find the section for quest mods. Allowing for collapsing all categories can make looking for quest mods much easier.

I have some experience in Svelte, so I can try my hand on implementing this feature. Not sure what's the policy for contributing, but I am interested since I use this site a lot xD

Thanks.

**Comment by phinocio** [comment]
Sorry for the slow reply!

I really like this idea, and I'm definitely open to PRs, though I have been considering switching to Nuxt from Sveltekit recently fwiw, but that'd still be a ways off.

**Comment by nollidnosnhoj** [comment]
Here's a pull request: https://github.com/phinocio/loadorderlibrary-frontend/pull/18
